### ISSUE TITLE
./tools not working on ubuntu 14.04 Chromebook

### ISSUE THREAD

**Issue by reedb** [hundredrabbits/Orca-c#14]
Multiple errors of this form:
  tui_main.c:1:0: error: bad value (nehalem) for -march= switch

Removed the following from ./tool and was able to compile with out errors:
  case $arch in
    x86_64) add cc_flags -march=nehalem;;
  esac

gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)
Ubuntu 14.04.5 LTS
Intel(R) Core(TM) i3-5015U CPU @ 2.10GHz

**Comment by cancel** [comment]
Thanks for reporting. I'll take a look in a couple of days, when I get the chance. I will probably need to figure out which versions of gcc have which arch flags available.
